title: Electronic Design
description: Concevez, prototypez et réalisez vos cartes électroniques
theme: bulma-clean-theme
url: https://makerspace-amiens.fr/electronic-design

force_theme: light
permalink: pretty
footer_menu: footer_navigation
lang: fr
theme_color: '#ef2e31'
fixed_navbar: top
favicon: favicon.png

paginate: 5
paginate_path: "/blog/page:num"

collections:
  docs:
    output: true
    layout: documentation
    image: https://via.placeholder.com/800x600
    show_sidebar: false
